blank_issues_enabled: true
contact_links:
  - name: ğŸ”— Create new issue / åˆ›å»ºæ–° issue
    url: https://issue.element-plus.org/
    about: Issues created using the âš ï¸ Blank issue above will be closed directly. Please click this link to create an issue using the issue helper. / ä½¿ç”¨ä¸Šé¢ âš ï¸ Blank issue åˆ›å»ºçš„é—®é¢˜å°†ä¼šè¢«ç›´æ¥å…³é—­ï¼Œè¯·ç‚¹å‡»æ­¤é“¾æ¥é€šè¿‡ issue helper åˆ›å»º.
  - name: ğŸ¤” Questions and Help / é—®é¢˜å’Œå¸®åŠ©
    url: https://github.com/element-plus/element-plus/discussions
    about: Ask questions and request help or other discussions.
