name: Issue Month Statistics

on:
  schedule:
    - cron: '0 1 1 * *'

jobs:
  month-statistics:
    runs-on: ubuntu-latest
    if: ${{ github.repository_owner == 'element-plus' }}
    steps:
      - name: month-statistics
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'month-statistics'
          token: ${{ secrets.GITHUB_TOKEN }}
          count-lables: 'true'
