name: Preview Start

on: pull_request_target

jobs:
  preview:
    runs-on: ubuntu-latest
    steps:
      - name: create
        uses: actions-cool/maintain-one-comment@v2.0.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          body: |
            <img width="400" src="https://user-images.githubusercontent.com/17680888/145600226-14f9cb31-33b8-4757-b2c0-affdb7499089.png">
            <!-- ELEMENT_PLUS_PREVIEW -->
          body-include: '<!-- ELEMENT_PLUS_PREVIEW -->'
