name: Website Preview

on: pull_request

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      PULL_REQUEST_NUMBER: ${{ github.event.number }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          registry-url: https://registry.npmjs.com/

      - name: Install dependencies
        run: yarn bootstrap

      - name: Init docs
        run: cd docs && yarn

      - name: generate common locale
        run: yarn docs:gen-locale

      - name: Build website
        run: yarn docs:build

      # share website dist
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: docs
          path: docs/.vitepress/dist/
          retention-days: 1

      # write pr.txt for share
      - name: Save pr number
        if: ${{ always() }}
        run: echo ${PULL_REQUEST_NUMBER} > ./pr.txt

      # share pr number
      - name: Upload pr number
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: pr
          path: ./pr.txt
          retention-days: 1
