name: Publish

on:
  release:
    types: [created]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install dependencies
        run: yarn bootstrap
      - name: Lint
        run: yarn lint
      - name: Test
        run: yarn test

  publish-npm:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          registry-url: https://registry.npmjs.com/
      - name: Get version
        run: echo "TAG_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Get git head
        run: echo "GIT_HEAD=${GITHUB_SHA}" >> $GITHUB_ENV
      - name: Gen npmrc
        run: echo "//registry.npmjs.com/:_authToken=${{ secrets.NPM_PUBLISH_TOKEN }}" > ./.npmrc
      - name: Build&publish
        run: sh ./scripts/publish.sh
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_PUBLISH_TOKEN}}
          TAG_VERSION: ${{env.TAG_VERSION}}
          GIT_HEAD: ${{env.GIT_HEAD}}
          REGISTRY: https://registry.npmjs.com/

  deploy-website:
    needs: publish-npm
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: yarn bootstrap

      - name: Init docs
        run: cd docs && yarn

      - name: Init Crowdin token
        run: yarn docs:crowdin
        env:
          CROWDIN_TOKEN: ${{secrets.CROWDIN_TOKEN}}

      - name: Upload source files
        run: cd docs && yarn crowdin upload sources

      - name: Pull Crowdin translations
        run: cd docs && yarn crowdin download

      - name: Generate common locale
        run: yarn docs:gen-locale

      - name: Build website
        run: yarn docs:build
        env:
          DOC_ENV: production

      # - name: Build Indices
      #   run: yarn build:indices
      #   env:
      #     ALGOLIA_KEY: ${{secrets.ALGOLIA_KEY}}

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: docs/.vitepress/dist
          GIT_CONFIG_NAME: ElementPlusBot
          GIT_CONFIG_EMAIL: hello@element-plus.org
          COMMIT_MESSAGE: website deploy

      - name: Sync
        env:
          TRIGGERSYNCURL: ${{ secrets.TRIGGERSYNCURL }}
        run: curl "$TRIGGERSYNCURL"
