name: Staging Preview

on:
  push:
    branches:
      - 'dev'
      - 'epic/website-refactor'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: yarn bootstrap

      - name: Compile Element Plus
        run: sh scripts/build.sh

      - name: Init docs
        run: cd docs && yarn

      - name: Init Crowdin token
        run: yarn init:crowdin
        env:
          CROWDIN_TOKEN: ${{secrets.CROWDIN_TOKEN}}

      - name: Upload source files
        run: cd docs && yarn crowdin upload source

      - name: Pull Crowdin translations
        run: cd docs && yarn crowdin download

      - name: generate common locale
        run: yarn docs:gen-locale

      - name: Build website
        run: yarn docs:build

      - name: Deploy Site
        run: |
          export DEPLOY_DOMAIN=https://staging-preview-element-plus.surge.sh
          echo "Deploy to $DEPLOY_DOMAIN"
          npx surge --project ./docs/.vitepress/dist/ --domain $DEPLOY_DOMAIN --token $SURGE_TOKEN
        env:
          SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}
